apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aliyun-exporter.fullname" . }}-config
  labels:
    {{- include "aliyun-exporter.labels" . | nindent 4 }}
data:
  aliyun.yaml: |
    {{- tpl .Values.config . | nindent 4 }}
