apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aliyun-exporter.fullname" . }}-env
  labels:
    {{- include "aliyun-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.extraSecretsEnv }}
  {{- toYaml . | nindent 2 }}
{{- end }}
