apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aliyun-exporter.fullname" . }}
  labels:
    {{- include "aliyun-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aliyun-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aliyun-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- if and .Values.imagePullSecrets (not .Values.serviceAccount.create) }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aliyun-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9107
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.extraSecretsEnv }}
          envFrom:
            - secretRef:
                name: {{ include "aliyun-exporter.fullname" . }}-env
          {{- end }}
          volumeMounts:
            - mountPath: /srv/ali-exporter/config/
              name: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "aliyun-exporter.fullname" . }}-config
