{{ if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aliyun-exporter.fullname" . }}
  {{- if .Values.serviceMonitor.labels }}
  labels:
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval | default "60s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "30s" }}
      honorTimestamps: true
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "aliyun-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
